name: Lint GitHub Actions files

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  lint-github-actions-files:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@7eeec1dd160c2301eb28e1568721837d084558ad # v1.57.0
        with:
          tool_name: actionlint
          reporter: github-pr-review
          fail_on_error: true
