name: Publishing to npm
on:
  push:
    branches:
      - main
    tags:
      - "!*"
    paths:
      - 'package.json'

jobs:
  check-version:
    name: Checking whether it can be published or not
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setting up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - name: Executing can-npm-publish
        run: npx can-npm-publish --verbose

  release:
    name: Releasing
    needs: check-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setting up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - name: Installing dependencies
        run: |
          npm ci

      - name: Build package
        run: npm run build:publish

      - name: Publishing to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
