name: tagpr

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  tagpr:
    name: Create release PR or tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: Songmu/tagpr@ecaea50544a6e1e288648b4e21eea0891de2c1a7 # v1.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
